### ISSUE TITLE
Demo issue (ignore)

### ISSUE THREAD

**Issue by mau-ferrusca** [yamassan-ramen/yum-yum-code#1]
Just checking how this part of GitHub works.

**Comment by mau-ferrusca** [comment]
Follow-up comment. You can STILL ignore this.

**Comment by maucincomdos** [comment]
@mau-ferrusca If I cared, I would comment here and add something useful. But I'll ignore it.

**Comment by mau-ferrusca** [comment]
Let's suppose the issue was fixed and I will close this comment thread.
